import { BeatJudgement } from '../BeatTypes';
import { MiningRangeHint, MiningRock } from '../MiningRock';
import { MINING_POINT_OFFSET, PlayerControlState, SwingPlan } from '../Player';
import { CompletionRating, CompletionSummary } from '../UIController';
import { GameModeId, MiningGameMode, MiningModeHost } from './MiningGameMode';

const RANGE = 92;
const ASSIST = 24;
type TargetState = 'none' | 'tooFar' | 'assist' | 'inRange' | 'facingWrong';
function rejected(): SwingPlan { return { accepted: false, impactHoldSeconds: 0, onImpact: () => undefined }; }

export class ClassicMiningMode implements MiningGameMode {
    readonly id: GameModeId = 'classic';
    private readonly plans = [
        { x: -350, kind: 'normal' as const, hp: 3, drops: 1 }, { x: -165, kind: 'normal' as const, hp: 4, drops: 1 }, { x: 25, kind: 'hard' as const, hp: 5, drops: 1 }, { x: 205, kind: 'normal' as const, hp: 4, drops: 1 }, { x: 365, kind: 'hard' as const, hp: 6, drops: 2 }, { x: 515, kind: 'crystal' as const, hp: 9, drops: 3 },
    ];
    private combo = 0; private perfectStreak = 0; private hotHand = false; private oreCount = 0; private perfect = 0; private good = 0; private miss = 0; private maxCombo = 0; private timingTotal = 0; private timingSamples = 0; private startedAt: number | null = null; private completed = false; private broken = 0; private ignored = 0; private targetState: TargetState = 'none'; private highlighted: MiningRock | null = null; private highlightedHint: MiningRangeHint = 'none'; private pendingImpact = false; private disposed = false;
    constructor(private readonly host: MiningModeHost) {}
    start(): void { this.restart(); }
    restart(): void { this.disposed = false; this.clearState(); this.host.clearEntities(); this.host.resetUi('classic'); this.host.setPlayerPosition(-510); this.plans.forEach((plan) => this.host.spawnRock(plan, (rock, x) => this.onBroken(rock, x, plan))); this.host.ui.setProgress(0, this.plans.length, true); }
    update(_dt: number): void { if (this.disposed || this.completed) return; this.updateTargetHint(); }
    handleBeat(): void {}
    handleMineInput(): SwingPlan { if (this.completed) return rejected(); if (this.host.calibration.isSampling) { this.host.calibration.recordTap(performance.now()); return rejected(); } if (this.host.calibration.blocksGameplay) return rejected(); const preview = this.host.beat.previewNow(); if (preview.consumed) { this.ignored++; this.pendingImpact = false; this.host.ui.showTooFast(); return rejected(); } const { state, target } = this.resolveTarget(); if (state !== 'inRange' && state !== 'assist') { this.host.audio.playSwing(); this.pendingImpact = false; this.host.ui.showSpatialHint(state, preview.offsetSeconds); return rejected(); } if (this.startedAt === null) this.startedAt = performance.now(); this.host.audio.playSwing(); this.host.beat.consumeBeatSlot(preview.targetBeatIndex); const judgement = preview.judgement; const hotBefore = this.hotHand; if (judgement === BeatJudgement.Miss) { this.combo = 0; this.perfectStreak = 0; this.hotHand = false; this.miss++; } else { this.combo++; this.maxCombo = Math.max(this.maxCombo, this.combo); if (judgement === BeatJudgement.Perfect) { this.perfect++; this.perfectStreak++; if (this.perfectStreak >= 3) this.hotHand = true; } else { this.good++; this.perfectStreak = 0; this.hotHand = false; } } this.timingSamples++; this.timingTotal += Math.abs(preview.offsetSeconds * 1000); this.host.ui.showJudgement(judgement, this.combo, preview.offsetSeconds, true); this.host.ui.updateStats(this.perfect, this.good, this.miss, this.maxCombo, this.average); this.host.ui.setHotHand(this.hotHand); if (judgement !== BeatJudgement.Miss) this.host.ui.fadeHelpAfterFirstValidHit(); const damage = judgement === BeatJudgement.Perfect && hotBefore ? 3 : preview.damage; this.pendingImpact = judgement !== BeatJudgement.Miss; return { accepted: true, impactHoldSeconds: judgement === BeatJudgement.Perfect ? 0.03 : judgement === BeatJudgement.Good ? 0.012 : 0, assistStep: state === 'assist' && target ? this.assistStep(target) : undefined, onImpact: () => { this.pendingImpact = false; if (judgement === BeatJudgement.Miss || !target?.isValid || !target.node.isValid) return; target.takeHit(damage, judgement, this.perfectStreak, hotBefore); if (judgement === BeatJudgement.Perfect) this.host.audio.playPerfect(hotBefore); else this.host.audio.playGood(); this.host.shake(judgement === BeatJudgement.Perfect ? 8 : 3); } }; }
    controlState(): PlayerControlState { return { canMove: !this.host.calibration.blocksGameplay, canMine: !this.host.calibration.blocksGameplay }; }
    shouldAutoCollect(): boolean { return false; }
    onOreCollected(): void { this.oreCount++; if (!this.completed && this.host.rocks.length === 0 && this.host.ores.length === 0 && this.host.collectingOres === 0) { this.completed = true; this.host.complete(this.summary()); } }
    dispose(): void { this.disposed = true; if (this.highlighted?.isValid) this.highlighted.setRangeHint('none'); }
    debugState(): object { return { combo: this.combo, perfectStreak: this.perfectStreak, hotHand: this.hotHand, perfectCount: this.perfect, goodCount: this.good, missCount: this.miss, maxCombo: this.maxCombo, oreCount: this.oreCount, rocks: this.host.rocks.length, targetState: this.targetState, rockInRange: this.targetState === 'inRange', ignoredInputCount: this.ignored, impactPending: this.pendingImpact, completed: this.completed, accuracyPercent: this.accuracy, rating: this.rating }; }
    private onBroken(_rock: MiningRock, x: number, plan: typeof this.plans[number]): void { this.broken++; this.host.audio.playRockBreak(); for (let i = 0; i < plan.drops; i++) this.host.spawnOre(x + (i - (plan.drops - 1) / 2) * 25, plan.kind === 'crystal'); this.host.ui.setProgress(this.broken, this.plans.length, this.host.rocks.some((rock) => rock.rockKind === 'crystal')); if (plan.kind === 'crystal') { this.host.ui.showFinalBreak(); this.host.shake(14); } }
    private resolveTarget(): { state: TargetState; target?: MiningRock } { const rocks = this.host.rocks.filter((rock) => rock.isValid && rock.node.isValid); if (!rocks.length) return { state: 'none' }; const facing = this.host.player.facingDirection; const playerX = this.host.player.worldX; const point = this.host.player.miningPointX; const ahead = rocks.filter((rock) => (rock.node.position.x - playerX) * facing >= 0).sort((a, b) => Math.abs(a.node.position.x - point) - Math.abs(b.node.position.x - point)); const next = ahead[0]; if (next) { const distance = Math.abs(next.node.position.x - point); if (distance <= RANGE) return { state: 'inRange', target: next }; if (distance <= RANGE + ASSIST) return { state: 'assist', target: next }; } const turnPoint = playerX - facing * MINING_POINT_OFFSET; const behind = rocks.filter((rock) => (rock.node.position.x - playerX) * facing < 0).sort((a, b) => Math.abs(a.node.position.x - turnPoint) - Math.abs(b.node.position.x - turnPoint))[0]; if (behind && Math.abs(behind.node.position.x - turnPoint) <= RANGE + ASSIST) return { state: 'facingWrong', target: behind }; return { state: 'tooFar', target: next }; }
    private updateTargetHint(): void { const { state, target } = this.resolveTarget(); this.targetState = state; const hint: MiningRangeHint = state === 'inRange' ? 'full' : state === 'assist' ? 'weak' : 'none'; const next = hint === 'none' ? null : target ?? null; if (this.highlighted && this.highlighted !== next && this.highlighted.isValid) this.highlighted.setRangeHint('none'); if (next && (this.highlighted !== next || this.highlightedHint !== hint)) next.setRangeHint(hint); this.highlighted = next; this.highlightedHint = hint; }
    private assistStep(target: MiningRock) { const targetX = target.node.position.x - this.host.player.facingDirection * (RANGE + MINING_POINT_OFFSET); const distance = Math.min(ASSIST, Math.abs(targetX - this.host.player.worldX)); return { targetX, durationSeconds: 0.06 + distance / ASSIST * 0.03 }; }
    private clearState(): void { this.combo = 0; this.perfectStreak = 0; this.hotHand = false; this.oreCount = 0; this.perfect = 0; this.good = 0; this.miss = 0; this.maxCombo = 0; this.timingTotal = 0; this.timingSamples = 0; this.startedAt = null; this.completed = false; this.broken = 0; this.ignored = 0; this.pendingImpact = false; this.targetState = 'none'; this.highlighted = null; this.highlightedHint = 'none'; }
    private get average(): number { return this.timingSamples ? this.timingTotal / this.timingSamples : Number.NaN; }
    private get accuracy(): number { const total = this.perfect + this.good + this.miss; return total ? (this.perfect * 100 + this.good * 60) / total : 0; }
    private get rating(): CompletionRating { if (this.accuracy >= 90 && this.miss === 0) return 'S'; if (this.accuracy >= 80) return 'A'; if (this.accuracy >= 65) return 'B'; return 'C'; }
    private summary(): CompletionSummary { const seconds = this.startedAt === null ? 0 : (performance.now() - this.startedAt) / 1000; return { seconds, oreCount: this.oreCount, perfect: this.perfect, good: this.good, miss: this.miss, maxCombo: this.maxCombo, averageAbsTimingMs: this.average, accuracyPercent: this.accuracy, rating: this.rating, nextGoal: this.miss > 0 ? '减少 Miss' : this.accuracy < 90 ? '提高 Perfect 比例' : '挑战更低用时或更高最大连击' }; }
}
