import { tween, Tween, Vec3 } from 'cc';
import { BeatJudgement } from '../BeatTypes';
import { MiningRock } from '../MiningRock';
import { PlayerControlState, SwingPlan } from '../Player';
import { CompletionRating, CompletionSummary } from '../UIController';
import { GameModeId, MiningGameMode, MiningModeHost } from './MiningGameMode';
import { PATTERN_LEVEL, PatternPhase, PatternSlotResult } from './PatternTypes';

function rejectedSwing(): SwingPlan { return { accepted: false, impactHoldSeconds: 0, onImpact: () => undefined }; }

export class PatternReplayMode implements MiningGameMode {
    readonly id: GameModeId = 'pattern';
    private phase: PatternPhase = 'positioning'; private rockIndex = 0; private attemptCount = 0;
    private listenStartBeatIndex = -1; private repeatStartBeatIndex = -1; private currentSlot = -1;
    private results: PatternSlotResult[] = []; private inputSlots = new Set<number>(); private lastBeatIndex = -1;
    private musicStarted = false; private cueCount = 0; private lastInputReason = 'waiting'; private suspendedReason: string | null = null;
    private successfulPatterns = 0; private failedPatterns = 0; private oreCount = 0; private perfect = 0; private good = 0; private miss = 0; private combo = 0; private maxCombo = 0; private timingTotal = 0; private timingSamples = 0; private startedAt: number | null = null; private completed = false; private disposed = false;

    constructor(private readonly host: MiningModeHost) {}
    start(): void { this.restart(); }
    restart(): void { this.disposed = false; this.clearState(); this.host.clearEntities(); this.host.resetUi('pattern'); PATTERN_LEVEL.forEach((level) => this.host.spawnRock({ x: level.x, kind: level.kind, hp: 1, drops: level.drops }, (rock, x) => this.onRockBroken(rock, x))); this.host.setPlayerPosition(-500); this.positionPlayer(); }
    update(_dt: number): void { if (this.disposed || this.completed) return; if (!this.host.audio.musicPlaying) { this.host.ui.showPatternMessage('按任意键开始音乐'); return; } if (!this.musicStarted) { this.musicStarted = true; this.phase = 'waitingForBar'; this.results = []; this.inputSlots.clear(); } if (this.host.calibration.blocksGameplay) { this.phase = 'suspended'; this.suspendedReason = 'settingsOrCalibration'; return; } if (this.phase === 'suspended') { this.resetAttempt(); this.suspendedReason = null; } if (this.phase === 'positioning') return; const level = PATTERN_LEVEL[this.rockIndex]; if (!level) return; if (this.phase === 'listening') this.currentSlot = Math.max(0, Math.min(3, Math.floor(this.host.beat.beatPosition - this.listenStartBeatIndex))); if (this.phase === 'repeating') this.currentSlot = Math.max(0, Math.min(3, Math.floor(this.host.beat.beatPosition - this.repeatStartBeatIndex))); this.host.ui.showPattern(this.phase === 'listening' ? '聆听' : this.phase === 'repeating' ? '轮到你' : '等待完整小节', level.pattern, this.results, this.attemptCount, this.rockIndex, this.currentSlot); }
    handleBeat(beatInBar: number, beatIndex: number): void { if (this.disposed || !this.host.audio.musicPlaying || this.host.calibration.blocksGameplay || this.completed) return; if (this.lastBeatIndex >= 0 && beatIndex < this.lastBeatIndex) this.resetAttempt(); this.lastBeatIndex = beatIndex; if (this.phase === 'waitingForBar' && beatInBar === 0) { this.phase = 'listening'; this.listenStartBeatIndex = beatIndex; this.currentSlot = 0; this.attemptCount++; if (PATTERN_LEVEL[this.rockIndex]?.pattern[0]) { this.host.audio.playPatternCue(true); this.cueCount++; } return; } const level = PATTERN_LEVEL[this.rockIndex]; if (!level) return; if (this.phase === 'listening') { const slot = beatIndex - this.listenStartBeatIndex; this.currentSlot = slot; if (slot > 0 && slot < 4 && level.pattern[slot]) { this.host.audio.playPatternCue(false); this.cueCount++; } if (slot >= 4) { this.phase = 'repeating'; this.repeatStartBeatIndex = beatIndex; this.currentSlot = 0; this.results = level.pattern.map((v) => v ? 'pending' : 'rest'); this.inputSlots.clear(); } return; } if (this.phase === 'repeating') { const slot = beatIndex - this.repeatStartBeatIndex - 1; if (slot >= 0 && slot < 4 && level.pattern[slot] && this.results[slot] === 'pending') { this.results[slot] = 'miss'; this.miss++; this.combo = 0; this.lastInputReason = 'missedRequired'; } if (beatIndex >= this.repeatStartBeatIndex + 4) this.resolve(level); } }
    handleMineInput(): SwingPlan { if (this.host.calibration.isSampling) { this.host.calibration.recordTap(performance.now()); return rejectedSwing(); } if (this.host.calibration.blocksGameplay || this.phase !== 'repeating') { this.host.ui.showPatternMessage(this.phase === 'listening' ? '先听节奏' : '等待节奏'); return rejectedSwing(); } const level = PATTERN_LEVEL[this.rockIndex]; const preview = this.host.beat.previewNow(); const slot = preview.targetBeatIndex - this.repeatStartBeatIndex; if (slot < 0 || slot > 3 || this.inputSlots.has(slot)) { this.lastInputReason = 'tooFast'; this.host.ui.showTooFast(); return rejectedSwing(); } this.inputSlots.add(slot); if (this.startedAt === null) this.startedAt = performance.now(); if (!level.pattern[slot]) { this.results[slot] = 'wrongRest'; this.miss++; this.combo = 0; this.lastInputReason = 'wrongRest'; this.host.ui.showPatternMessage('休止误按'); return rejectedSwing(); } const judgement = preview.judgement; this.results[slot] = judgement === BeatJudgement.Perfect ? 'perfect' : judgement === BeatJudgement.Good ? 'good' : 'miss'; if (judgement === BeatJudgement.Perfect) { this.perfect++; this.combo++; } else if (judgement === BeatJudgement.Good) { this.good++; this.combo++; } else { this.miss++; this.combo = 0; } this.maxCombo = Math.max(this.maxCombo, this.combo); this.timingSamples++; this.timingTotal += Math.abs(preview.offsetSeconds * 1000); this.lastInputReason = judgement.toLowerCase(); this.host.ui.showJudgement(judgement, this.combo, preview.offsetSeconds, true); return rejectedSwing(); }
    controlState(): PlayerControlState { return { canMove: false, canMine: this.phase === 'repeating' && !this.host.calibration.blocksGameplay }; }
    shouldAutoCollect(): boolean { return true; }
    onOreCollected(): void { this.oreCount++; if (!this.completed && this.host.rocks.length === 0 && this.host.ores.length === 0 && this.host.collectingOres === 0) { this.completed = true; this.host.complete(this.summary()); } }
    dispose(): void { this.disposed = true; Tween.stopAllByTarget(this.host.player.node); this.results = []; this.inputSlots.clear(); }
    debugState(): object { return { phase: this.phase, currentRockIndex: this.rockIndex, pattern: PATTERN_LEVEL[this.rockIndex]?.pattern ?? [], listenStartBeatIndex: this.listenStartBeatIndex, repeatStartBeatIndex: this.repeatStartBeatIndex, currentSlot: this.currentSlot, cueCount: this.cueCount, slotResults: this.results, lastInputReason: this.lastInputReason, attemptCount: this.attemptCount, successfulPatterns: this.successfulPatterns, failedPatterns: this.failedPatterns, perfect: this.perfect, good: this.good, miss: this.miss, maxCombo: this.maxCombo, accuracyPercent: this.accuracy, rating: this.rating, suspendedReason: this.suspendedReason, rocks: this.host.rocks.length, ores: this.host.ores.length, oreCount: this.oreCount, completed: this.completed }; }
    private onRockBroken(_rock: MiningRock, x: number): void { const level = PATTERN_LEVEL[this.rockIndex]; this.host.audio.playRockBreak(); for (let i = 0; i < level.drops; i++) this.host.spawnOre(x + (i - (level.drops - 1) / 2) * 25, level.kind === 'crystal'); }
    private resolve(level: typeof PATTERN_LEVEL[number]): void { const ok = this.results.every((value, index) => level.pattern[index] ? value === 'perfect' || value === 'good' : value === 'rest'); if (!ok) { this.failedPatterns++; this.host.ui.showPatternMessage('复刻失败 · 下一小节重试'); this.resetAttempt(); return; } this.successfulPatterns++; this.phase = 'collecting'; this.host.ui.showPatternMessage(this.results.some((v) => v === 'good') ? '复刻成功' : '完美复刻'); const target = this.host.rocks.reduce((best, rock) => !best || Math.abs(rock.node.position.x - level.x) < Math.abs(best.node.position.x - level.x) ? rock : best, null as MiningRock | null); if (target) target.takeHit(1, BeatJudgement.Perfect, 0); this.rockIndex++; if (this.rockIndex >= PATTERN_LEVEL.length) this.phase = 'complete'; else this.positionPlayer(); }
    private positionPlayer(): void { const level = PATTERN_LEVEL[this.rockIndex]; if (!level) return; this.phase = 'positioning'; const targetX = Math.max(-540, Math.min(540, level.x - 164)); tween(this.host.player.node).to(0.3, { position: new Vec3(targetX, -205, 0) }).call(() => { if (!this.disposed && this.phase === 'positioning') this.phase = 'waitingForBar'; }).start(); }
    private resetAttempt(): void { this.phase = 'waitingForBar'; this.results = []; this.inputSlots.clear(); this.currentSlot = -1; }
    private clearState(): void { this.phase = 'positioning'; this.rockIndex = 0; this.attemptCount = 0; this.listenStartBeatIndex = -1; this.repeatStartBeatIndex = -1; this.currentSlot = -1; this.results = []; this.inputSlots.clear(); this.lastBeatIndex = -1; this.musicStarted = false; this.cueCount = 0; this.lastInputReason = 'waiting'; this.suspendedReason = null; this.successfulPatterns = 0; this.failedPatterns = 0; this.oreCount = 0; this.perfect = 0; this.good = 0; this.miss = 0; this.combo = 0; this.maxCombo = 0; this.timingTotal = 0; this.timingSamples = 0; this.startedAt = null; this.completed = false; }
    private get accuracy(): number { const total = this.perfect + this.good + this.miss; return total === 0 ? 0 : (this.perfect * 100 + this.good * 60) / total; }
    private get rating(): CompletionRating { if (this.accuracy >= 90 && this.miss === 0) return 'S'; if (this.accuracy >= 80) return 'A'; if (this.accuracy >= 65) return 'B'; return 'C'; }
    private summary(): CompletionSummary { const seconds = this.startedAt === null ? 0 : (performance.now() - this.startedAt) / 1000; return { seconds, oreCount: this.oreCount, perfect: this.perfect, good: this.good, miss: this.miss, maxCombo: this.maxCombo, averageAbsTimingMs: this.timingSamples ? this.timingTotal / this.timingSamples : Number.NaN, accuracyPercent: this.accuracy, rating: this.rating, nextGoal: this.miss > 0 ? '减少 Miss' : this.accuracy < 90 ? '提高 Perfect 比例' : '挑战更低用时或更高最大连击', successfulPatterns: this.successfulPatterns, failedPatterns: this.failedPatterns }; }
}
